version: '3'
services:
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: -------
      MYSQL_DATABASE: Scraping
    volumes:
      - db_data:/var/lib/mysql
  fastapi_app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db

volumes:
  db_data:
